- name: Instalar y correr Docker container
  hosts: local
  become: yes

  tasks:
    - name: Instalar Docker
      dnf:
        name: docker
        state: present

    - name: Iniciar Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Instalar pip
      dnf:
        name: python3-pip
        state: present

    - name: Instalar docker SDK para Python
      pip:
        name: docker

    - name: Levantar contenedor nginx
      community.docker.docker_container:
        name: nginx-test
        image: nginx
        state: started
        ports:
          - "8081:80"